### ISSUE TITLE
How do you call audit programatically?

### ISSUE THREAD

**Issue by mgzenitech** [twu/skjold#133]
I need to skip the cli and call **audit_** directly from my package. Not sure how I am supposed to do that since you use click decorators. Any help would be appreciated!

Currently what I am trying:
`pyproject.toml`
```
[tool.skjold]
    sources = ["gemnasium"]
    cache_dir = "./tmp/skjold_cache"
```

```python
from skjold.cli import audit_

audit_(["-r", "-o", "cli", "-i=", "-s", "gemnasium", "Pipfile.lock"])
```
Yet it fails since in `pyproject.toml` I have changed the location of cache:
```
Traceback (most recent call last):
..........
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/lib/python/cli/commands/check_packages.py", line 19, in check_packages
    audit_([
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/skjold/cli.py", line 184, in audit_
    findings = audit(config, packages, ignore=ignore)
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/skjold/tasks.py", line 221, in audit
    if source.has_security_advisory_for(package_name):
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/skjold/sources/gemnasium.py", line 130, in has_security_advisory_for
    return package_name.strip().lower() in self.advisories.keys()
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/skjold/models.py", line 101, in advisories
    self.update()
  File "/home/xxx/Documents/Projects/yyy/projects/ppp/.virtualenv/lib/python3.9/site-packages/skjold/sources/gemnasium.py", line 126, in update
    with open(self.path, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '.skjold_cache/gemnasium.cache'
```

Looks like if I try to call audit_ directly it looses all configuration settings.

**Comment by mgzenitech** [comment]
Nevermind :) Figured out by myself:
```python
#!/usr/bin/env -S pipenv run python

from pathlib import Path
from typing import Any
from click import secho
from skjold.formats import extract_package_list_from
from skjold.tasks import Configuration, audit, report, get_configuration_from_toml
from skjold.ignore import SkjoldIgnore
from skjold.models import PackageList

# Import triggers register of this source
# pylint: disable-next=unused-variable, unused-import
import skjold.sources.gemnasium

def check_packages() -> None:
    config: Configuration = Configuration()
    settings: dict[str, Any] = get_configuration_from_toml("pyproject.toml")
    config.use(settings)
    cache_dir: Path = Path(config.cache_dir)
    cache_dir.mkdir(parents = True, exist_ok = True)
    with open("Pipfile.lock", "r", encoding = "utf-8") as pipfile:
        packages: PackageList = extract_package_list_from(config, pipfile)
    secho("Checking ", nl = False, err = True)
    secho(len(packages), fg = "green", nl = False, err = True)
    secho(" package(s) using ", nl = False, err = True)
    secho(config.sources, fg = "green", nl = False, err = True)
    secho(" as source(s).\n", err = True)
    ignore: SkjoldIgnore = SkjoldIgnore.using(config.ignore_file)
    findings: list[dict[str, Any]] = audit(config, packages, ignore)
    vulnerable_packages, _ = report(config, findings)
    if len(vulnerable_packages) > 0:
        raise SystemExit(1)

if __name__ == "__main__": # pragma: no cover
    check_packages()

```
