### ISSUE TITLE
pypa audits raise ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by brondsem** [twu/skjold#150]
`pypa` audits started failing in the past day or so.  Here's an example:

```
$ rm -rf .skjold_cache/
$ echo 'bottle==0.12.23' | skjold audit -s pypa -
Warning: No 'pyproject.toml' found!
Traceback (most recent call last):
  File "../env/bin/skjold", line 8, in <module>
    sys.exit(cli())
  File "../env/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "../env/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "../env/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "../env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "../env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "../env/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "../env/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "../env/lib/python3.7/site-packages/skjold/cli.py", line 184, in audit_
    findings = audit(config, packages, ignore=ignore)
  File "../env/lib/python3.7/site-packages/skjold/tasks.py", line 225, in audit
    if source.has_security_advisory_for(dependency):
  File "../env/lib/python3.7/site-packages/skjold/sources/pypa.py", line 65, in has_security_advisory_for
    return dependency.canonical_name in self.advisories.keys()
  File "../env/lib/python3.7/site-packages/skjold/core.py", line 123, in advisories
    self.populate_from_cache()
  File "../env/lib/python3.7/site-packages/skjold/sources/pypa.py", line 43, in populate_from_cache
    doc = yaml.load(obj_fh, Loader=yaml.SafeLoader)
  File "../env/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "../env/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "../env/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "../env/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "../env/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "../env/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "../env/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "../env/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "../env/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "../env/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "../env/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in ".skjold_cache/pypa.cache", line 2, column 98
```

**Comment by twu** [comment]
👋 @brondsem Seems like an issue with `vulns/py/PYSEC-2022-42969.yaml` containing a colon. Already got reported https://github.com/pypa/advisory-database/issues/106. Proposed a fix in https://github.com/pypa/advisory-database/pull/107. Either way this should sort itself out soon 🤞. HTH

**Comment by twu** [comment]
@brondsem PR got merged and `pypa` appears to be working again.

```sh
$ rm -rf .skjold_cache
$ echo 'bottle==0.12.23' | skjold audit -s pypa -
No vulnerable packages found!
```

HTH :)
